language: csharp
solution: sync.today.travis.sln
before_script:
  - find . -name "*.config" -type f -print | xargs perl -pe 's|\Q"Server=(localdb)\ProjectsV12; Database=SyncToday2015.new; Trusted_Connection=True;"\E|"Data Source=kc8q88iui6.database.windows.net;Initial Catalog=sync.today.db.test;Integrated Security=False;User ID=sync.today;Password=Betpum57;Connect Timeout=60;Encrypt=False;TrustServerCertificate=False"|g'
