# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://localhost:8080
gitlocation: https://github.com/SyncToday/synctoday2015.git
gitbranch: gh-pages
title: Sync.Today - Business Processes Automation Platform
description: >
    It is an application integration server.
    Exchanging business documents among different systems both within or across organizational boundaries Sync.Today integrates business processes.
    Sync.Today is like an Instagram filter to your business data.
    It can enhance the information you already have in your information systems to bring you the greatest benefits.

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
